#pragma config(Sensor, dgtl2,  mot3sensor,     sensorQuadEncoder)
#pragma config(Sensor, dgtl4,  mot1sensor,     sensorQuadEncoder)
#pragma config(Motor,  port2,           mot1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           mot2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           mot3,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           mot4,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mot5,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mot6,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           mot7,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	//Varibale declaration
	short yesNo=0;

	// Run in constant loop
	while(1){
		// If the right joystick (horizontal) is on
		if(vexRT[Ch1] != 0){
			//Set motors in same direction
			bMotorReflected[mot1] = true;
			bMotorReflected[mot2] = true;

			//Set motor speeds
			motor[mot1] = vexRT[Ch1];
			motor[mot2] = vexRT[Ch1];
			motor[mot3] = vexRT[Ch1];
			motor[mot4] = vexRT[Ch1];

			//Set motors to running
			yesNo=1;
		}
		else{
			//Set motors to not running
			yesNo=0;
		}

		//If left joystick is on (any axis)
		if (vexRT[Ch3]>20 || vexRT[Ch4]>20 || vexRT[Ch3]<-20 || vexRT[Ch4]<-20){
			//Set motor directions to parallel
			bMotorReflected[mot1] = false;
			bMotorReflected[mot2] = false;

			//Set motor speeds
			motor[mot1] = (((float)215)/255)*vexRT[Ch3];
			motor[mot2] = vexRT[Ch4]; //(((float)205)/255)
			motor[mot3] = vexRT[Ch3];
			motor[mot4] = vexRT[Ch4];

			//No motors running
			}else if (yesNo==0){
			//Set motor speeds to 0
			motor[mot1] = 0;
			motor[mot2] = 0;
			motor[mot3] = 0;
			motor[mot4] = 0;
		}

		//Check if button has been clicked (right up and down)
		if(vexRT[Btn8U] != 0 || vexRT[Btn8D] != 0){
			//If right down
			if(vexRT[Btn8D] != 0)
				bMotorReflected[mot5] = true;
			else //Right up
				bMotorReflected[mot5]= false;
			motor[mot5] = 100; //Set motor speed
		}
		else{
			//Right down
			if(vexRT[Btn8D] != 0)
				bMotorReflected[mot5] = true;
			else //Right up
				bMotorReflected[mot5]= false;
			motor[mot5] = 20; //Set motor speed
		}

		//Check if button has been clicked (left or right)
		if(vexRT[Btn8R] != 0 || vexRT[Btn8L] != 0){
			if(vexRT[Btn8L] != 0) //If left clicked
				bMotorReflected[mot6] = true;
			else //If right clicked
				bMotorReflected[mot6]= false;
			motor[mot6] = 50; //Set motor speed
			}else{
			motor[mot6] = 0; //Shut off motor
		}

		//Check if button has been clicked (left or right)
		if(vexRT[Btn5U] != 0 || vexRT[Btn5D] != 0){
			// Left button clicked
			if(vexRT[Btn5U] != 0){
				bMotorReflected[mot7] = true;
			}
			//Right button clicked
			else {
				bMotorReflected[mot7] = false;
			}
			motor[mot7] = 40;
		}
		else{
			motor[mot7] = 0;
		}

		if(vexRT[Btn6U] != 0 || vexRT[Btn6D] != 0){
			//If right down
			if(vexRT[Btn6D] != 0){
				bMotorReflected[mot5] = true;
				motor[mot5] = 70; //Set motor speed
				delay(200);
				}else{ //Right up
				bMotorReflected[mot5]= false;
				motor[mot5] = 100; //Set motor speed
				delay(400);
			}
		}
		else{
			//Right down
			if(vexRT[Btn6D] != 0)
				bMotorReflected[mot5] = true;
			else //Right up
				bMotorReflected[mot5]= false;
			motor[mot5] = 20; //Set motor speed
		}
	}






	//signed long value1=0;
	//signed long value3=0;
	//clearDebugStream();
	////wait1Msec(1000);
	//// assume motor is on port 1
	//bMotorReflected[mot1] = false;
	//bMotorReflected[mot3] = true;
	//motor[ mot1 ] = 250;
	//motor[ mot3 ] = 210;
	//// delay while motor accelerates
	//wait1Msec( 500 );

	//// clear encoder, enc should be the digital port that the encoder is on
	//SensorValue[ mot1sensor ] = 0;
	//SensorValue[mot3sensor] = 0;

	//// wait for 1 second
	//wait1Msec(1000);							// 0.08 is the constant of distance (cm) / encoder value
	//														  // 47 cm/s
	//value1 = -SensorValue[ mot1sensor ];
	//value3 = SensorValue[ mot3sensor ];

	//// stop motor
	//motor[ mot1 ] = 0;
	//motor[ mot3 ] = 0;

	//// send to stdio
	//writeDebugStreamLine("mot1 sensor value: %d", value1 );
	//writeDebugStreamLine("mot3 sensor value: %d", value3 );

	//while(1)
	//	wait1Msec(10);
	//while(1){
	//	if(vexRT[Btn8U] != 0){
	//		//Set motor speeds
	//	  short speed = 250;
	//		motor[mot1] = (((float)215)/255)*speed;
	//		motor[mot3] = speed;
	//		wait1Msec(500);
	//		wait1Msec(3000);								// (180 cm - 30 cm) / 47 cm/s = 3.19
	//	}
	//}
}
